- name: installs dotfiles for root
  copy: src=root/{{ item }} dest=/root/.{{ item }} owner=root group=root
  with_items:
    - bashrc
    - tmux.conf
    - vimrc

- name: set up ssh authorized_key for root
  authorized_key: user=root key="{{ lookup('file', 'root/id_rsa.pub') }}"
